config/routes.rb
Rails.application.routes.draw do
  devise_for :user,skip: [:passwords], controllers: {
    registrations: 'public/registrations',
    sessions: 'public/sessions',
    passwords: 'public/passwords'#エラー起きるかも
  }

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: 'admin/sessions'
  }
  root to: 'public/homes#top'

  get 'home/about' => 'public/homes#about'
  devise_scope :user do
    post 'users/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end
  #カテゴリーの検索もいる
  scope module: :public do
    resources :users, only: [:index, :show, :edit, :update, :destroy] do
      resource :relationships, only: [:create, :destroy]
      get "followings" => "relationships#followings", as: "followings"
      get "followers" => "relationships#followers", as: "followers"
      resources :favorites, only:[:index]
      resources :bookmarks, only:[:index]#doの直下にすることでidを取得できる
      collection do
        get 'confirm' => 'users#confirm' #退会確認画面
        patch 'withdraw' => 'users#withdraw' #論理削除用のルーティング
      end
      member do
        #get :favorites
        get :favorited
      end
    end

    get "search" => "searches#search"
    get '/category/search' => 'searches#category_search'

    resources :items do
      resources :comments, only: [:create, :index, :destroy] #一覧もいるかも
      resource :favorites, only: [:create, :destroy]
      resource :bookmarks, only: [:create, :destroy]
    end

  end

  get 'admin' => 'admin/homes#top'
  namespace :admin do
    resources :items, only: [:index, :show, :destroy] do
      resources :comments, only: [:index, :destroy]
    end

    resources :categories, only: [:index, :create, :edit, :update, :destroy]
    resources :users, only: [:index, :show, :edit, :update, :destroy] do
        get 'confirm' => 'users#confirm'
        patch 'withdraw' => 'users#withdraw'
      end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  #has_one_attached :image
  belongs_to :user
  belongs_to :item

  validates_uniqueness_of :item_id, scope: :user_id
  validates :user_id, uniqueness: { scope: :item_id}

  #def get_image
   # unless image.attached?
    #  file_path = Rails.root.join('app/assets/images/no_image_square.jpg')
     # image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    #end
    #image
  #end
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :items, dependent: :destroy

  validates :name, presence: true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :item
  belongs_to :user

  validates :comment_content, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :item
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image
  belongs_to :user, optional: true
  belongs_to :category
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  has_many :favorited_users, through: :favorites, source: :user

  validates :name, presence: true
  validates :value, presence: true
  validates :review, presence: true
  validates :image, presence: true

  scope :latest, -> {order(created_at: :desc)} #最新のものから順に並べる
  scope :old, -> {order(created_at: :asc)} #古いものから順に並べる
  scope :star_count, -> {order(star: :desc)} #星の数が多い順に並べる
  #order データの取り出し
  #created_at 投稿日のカラム
  #desc 昇順
  #asc 降順

  def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image_square.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image
  end

  def favorited_by?(user)
    favorites.exists?(user_id: user.id) #ログインしてない場合エラーが出る
  end

  def self.favorited(user)
    includes(:favorites)
    .where(favorites: { user_id: user.id})
  end

  def bookmarked_by?(user)
    bookmarks.where(user_id: user).exists?
  end
end

app/models/post.rb
class Post < ApplicationRecord

end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/tag.rb
class Tag < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one_attached :profile_image
  has_many :items, :dependent => :destroy
  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  has_many :bookmarks_boards, through: :bookmarks, source: :board
  validates :name, presence:true

  def get_profile_image
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/figure_dance.png')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image
  end

  has_many :active_relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :passive_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followings, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower

  def follow(user)
    active_relationships.create(followed_id: user.id)
  end

  def unfollow(user)
    active_relationships.find_by(followed_id: user.id).destroy
  end

  def following?(user)
    followings.include?(user)
  end


  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "ゲスト"
    end
  end

  def own?(object)
    id == object.user_id
  end

  def bookmark(item)
    bookmarks_items << item
  end

  def unbookmark(board)
    bookmarks_items.delete(item)
  end

  def bookmark?(item)
    bookmarks_boards.include?(item)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!
  def top
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_admin!
  def index
    @users = User.all.page(params[:page]).per(5)
  end

  def show
    @user = User.find(params[:id])
    @items = @user.items
  end

  def edit
  end

  def confirm
    @user = User.find(params[:user_id])
  end

  def withdraw
    user = User.find(params[:user_id])#current_user？U
    user.update(is_active: false)
    Item.where(user_id: user).destroy_all#itemとそれに関連してる情報は削除される
    #reset_session
    redirect_to admin_path,notice: "退会処理を実行しました"
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmark_helper.rb
module BookmarkHelper
end

app/helpers/public_helper.rb
module PublicHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/views/admin/users/confirm.html.erb
<h1>本当に退会しますか？</h1>
  <p>
    退会すると、会員登録情報や<br>
    投稿が閲覧できなくなります。<br>
    退会する場合は、「退会する」をクリックしてください。
  </p>

  <%= link_to "退会しない", admin_users_path, :class => "btn btn-primary ms-3" %>
  <%= link_to "退会する", admin_user_withdraw_path(@user.id), method: :patch, :class => "btn btn-danger ms-3", data: { confirm: "本当に退会しますか？" }  %>

app/views/admin/users/edit.html.erb
<h1>Admin::Users#edit</h1>
<p>Find me in app/views/admin/users/edit.html.erb</p>

app/views/admin/users/index.html.erb
<table class="container table table-hover">
   <h4 class="p-4 font-weight-bold">ユーザー一覧</h4>
  <% @users.each do |user| %>
    <tr class="border-top border-bottom">
      <td><%= link_to admin_user_path(user.id) do %>
      <%= image_tag user.get_profile_image, size: "100x100" %><% end %>
      </td>
      <td><p><%= user.name %></p>
      <p>投稿数: <%= user.items.count %></p>
      </td>
    </tr>
  <% end %>
</table>
<div class="pagination justify-content-center">
  <%= paginate @users %><!--変わるかも-->
</div>

app/views/admin/users/show.html.erb
<h4 class="text-center p-4">ユーザー詳細</h4>
<div class="container">
  <div class="row">
    <div class="col-md-3">
    <div><%= image_tag @user.get_profile_image, size: "100x100" %></div>
    <div>ユーザー名: <%= @user.name %></div>
    <div>自己紹介: <%= @user.introduction %></div>
    <div>
      <% if @user.is_active == true %>
       <%= link_to "利用停止", admin_user_confirm_path(@user.id) %>
      <% end %>
    </div>
    <div><b>会員ステータス</b></div>
          <div>
            <% if @user.is_active == true %>
              <span class="text-success font-weight-bold">有効</span>
            <% elsif @user.is_active == false %>
              <span class="text-danger font-weight-bold">退会</span>
            <% end %>
          </div>
    <!--投稿したitem一覧-->
    </div>
    <div class="offset-md-3 col-md-6">
      <% @items.each do |item| %>
        <table>
          <tr class="border-top border-bottom">
            <td class="pr-5"><%= image_tag item.get_image, size: "100x100" %></td>
            <td><p><%= item.name %></p>
            <p>♡<%= item.favorites.count %></p>
            <p>コメント数:<%= item.comments.count %></p></td>
          </tr>
        </table>
      <% end %>
    </div>
  </div>
</div>