config/routes.rb
Rails.application.routes.draw do
  devise_for :user,skip: [:passwords], controllers: {
    registrations: 'public/registrations',
    sessions: 'public/sessions',
    passwords: 'public/passwords'#エラー起きるかも
  }

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: 'admin/sessions'
  }
  root to: 'public/homes#top'

  get 'home/about' => 'public/homes#about'
  devise_scope :user do
    post 'users/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end
  #カテゴリーの検索もいる
  scope module: :public do
    resources :users, only: [:index, :show, :edit, :update, :destroy] do
      resource :relationships, only: [:create, :destroy]
      get "followings" => "relationships#followings", as: "followings"
      get "followers" => "relationships#followers", as: "followers"
      resources :favorites, only:[:index]
      resources :bookmarks, only:[:index]#doの直下にすることでidを取得できる
      collection do
        get 'confirm' => 'users#confirm' #退会確認画面
        patch 'withdraw' => 'users#withdraw' #論理削除用のルーティング
      end
      member do
        #get :favorites
        get :favorited
      end
    end

    get "search" => "searches#search"
    get '/category/search' => 'searches#category_search'

    resources :items do
      resources :comments, only: [:create, :index, :destroy] #一覧もいるかも
      resource :favorites, only: [:create, :destroy]
      resource :bookmarks, only: [:create, :destroy]
    end

  end

  get 'admin' => 'admin/homes#top'
  namespace :admin do
    resources :items, only: [:index, :show, :destroy] do
      resources :comments, only: [:index, :destroy]
    end

    resources :categories, only: [:index, :create, :edit, :update, :destroy]
    resources :users, only: [:index, :show, :edit, :update, :destroy] do
        get 'confirm' => 'users#confirm'
        patch 'withdraw' => 'users#withdraw'
      end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  #has_one_attached :image
  belongs_to :user
  belongs_to :item

  validates_uniqueness_of :item_id, scope: :user_id
  validates :user_id, uniqueness: { scope: :item_id}

  #def get_image
   # unless image.attached?
    #  file_path = Rails.root.join('app/assets/images/no_image_square.jpg')
     # image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    #end
    #image
  #end
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :items, dependent: :destroy

  validates :name, presence: true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :item
  belongs_to :user

  validates :comment_content, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :item
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image
  belongs_to :user, optional: true
  belongs_to :category
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  has_many :favorited_users, through: :favorites, source: :user

  validates :name, presence: true
  validates :value, presence: true
  validates :review, presence: true
  validates :image, presence: true

  scope :latest, -> {order(created_at: :desc)} #最新のものから順に並べる
  scope :old, -> {order(created_at: :asc)} #古いものから順に並べる
  scope :star_count, -> {order(star: :desc)} #星の数が多い順に並べる
  #order データの取り出し
  #created_at 投稿日のカラム
  #desc 昇順
  #asc 降順

  def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image_square.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image
  end

  def favorited_by?(user)
    favorites.exists?(user_id: user.id) #ログインしてない場合エラーが出る
  end

  def self.favorited(user)
    includes(:favorites)
    .where(favorites: { user_id: user.id})
  end

  def bookmarked_by?(user)
    bookmarks.where(user_id: user).exists?
  end
end

app/models/post.rb
class Post < ApplicationRecord

end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/tag.rb
class Tag < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one_attached :profile_image
  has_many :items, :dependent => :destroy
  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  has_many :bookmarks_boards, through: :bookmarks, source: :board
  validates :name, presence:true

  def get_profile_image
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/figure_dance.png')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image
  end

  has_many :active_relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :passive_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followings, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower

  def follow(user)
    active_relationships.create(followed_id: user.id)
  end

  def unfollow(user)
    active_relationships.find_by(followed_id: user.id).destroy
  end

  def following?(user)
    followings.include?(user)
  end


  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "ゲスト"
    end
  end

  def own?(object)
    id == object.user_id
  end

  def bookmark(item)
    bookmarks_items << item
  end

  def unbookmark(board)
    bookmarks_items.delete(item)
  end

  def bookmark?(item)
    bookmarks_boards.include?(item)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmark_helper.rb
module BookmarkHelper
end

app/helpers/public_helper.rb
module PublicHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OtokoNoSkincare</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/04f10c2a51.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column vh-100">
   <header class="shadow-sm  bg-info">
    <nav class="navbar navbar-expand-lg navbar-light">
       <a href="/" class="navbar-brand ml-5"><%= image_tag('Fashion_Style-removebg-preview.png', size: "200x125") %></a>
        <%= form_with url: search_path, local: true, method: :get do |form| %><!--ここは変更濃厚-->
          <%= form.text_field :keyword %>
          <%= form.submit '検索' %>
        <% end %>
       <button class="navbar-toggler" type="button"
        data-toggle="collapse"
        data-target="#navbarNavDropdown"
        aria-controls="navbarNavDropdown"
        aria-expanded="false"
        aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span> <!--navbarの色がない-->
       </button>

   <div id="sp-menu">
     <h2>MENU</h2>
     <ul>
      <% if user_signed_in? %>
        <li>
          <%= link_to "マイページ", user_path(current_user.id), class: 'nav-link, text-white' %>
        </li>
        <li>
          <%= link_to "投稿一覧", items_path, class: 'nav-link, text-white'  %>
        </li>
        <li>
          <%= link_to "新規投稿", new_item_path, class: 'nav-link, text-white' %>
        </li>
        <li>
          <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'nav-link, text-white' %>
        </li>
        <% elsif admin_signed_in? %>
        <li>
          <%= link_to"会員一覧",admin_users_path, class: 'nav-link, text-white' %>
        </li>
        <li>
          <%= link_to"投稿一覧",admin_items_path, class: 'nav-link, text-white' %>
        </li>
        <li>
          <%= link_to"カテゴリー一覧",admin_categories_path, class: 'nav-link, text-white' %>
        </li>
         <li>
          <%= link_to"ログアウト",destroy_admin_session_path, method: :delete,class: 'nav-link, text-white' %>
        </li>
      <% else %>
        <li>
          <%= link_to "新規登録", new_user_registration_path, class: 'nav-link, text-white' %>
        </li>
        <li>
          <%= link_to "ログイン", new_user_session_path, class: 'nav-link, text-white' %>
        </li>
        <li>
          <%= link_to "ゲストログイン", users_guest_sign_in_path, class: 'nav-link, text-white', method: :post %>
        </li>
        <li>
          <%= link_to "About", home_about_path, class: 'nav-link, text-white' %>
        </li>
      <% end %>
    </ul>
   </div>

   <div id="hm-icon">
     <a class="menu-trigger" href="">
       <span></span>
       <span></span>
       <span></span>
     </a>
   </div>

    </nav>
   </header>
    <main>
      <div>
        <%= flash[:notice] %>
      </div>
     <%= yield %>
      <footer class="pt-5 pb-4">
        <p class="text-center" style="color: #291b25">Otoko-no-skin_care</p>
      </footer>
    </main>
  </body>
</html>

app/views/template/_index.html.erb
<% items.each do |item| %>
  <div class="col-3 border text-center">
    <div class= "post-item">
    <p><%= link_to item_path(item.id) do %>
    <%= image_tag item.get_image, class: 'image' %><% end %>
    </p>
      <div class="info">
        <p><%= link_to item.name, item_path(item.id) %></p>
        <p><%= link_to item.user.name , user_path(item.user.id) %></p><!--違うかもしれん-->
        <p id="favorite_btn_<%= item.id %>">
         <%= render "public/favorites/btn", item: item %>
        </p>
        <p>コメント数:<%= link_to item.comments.count, item_comments_path(item.id) %></p>
        <p><%= render 'template/static', item: item %></p>
      </div>
    </div>
  </div>
<% end %>

app/views/template/_static.html.erb
<div id="star_<%= item.id %>"></div>
<script>
$(document).on('turbolinks:load', function() {
  let elem = document.querySelector('#star_<%= item.id %>');
  if (elem == null) return;

  elem.innerHTML = "";
  let opt = {
    starOn: "<%= asset_path('star-on.png') %>",
    starOff: "<%= asset_path('star-off.png') %>",
    starHalf: "<%= asset_path('star-half.png') %>",
    score: "<%= item.star %>",
    readOnly: true,
  };
  raty(elem, opt);
});
</script>

app/views/template/_user.html.erb
<table class="container table table-hover">
  <% users.each do |user| %>
    <tr class="border-top border-bottom">
      <td><%= link_to user_path(user.id) do %>
      <%= image_tag user.get_profile_image, size: "100x100" %><% end %>
      </td>
      <td><p><%= user.name %></p>

      <p>投稿数: <%= user.items.count %></p></td>
    </tr>
  <% end %>
</table>